version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app1:
    build: .
    container_name: app1
    volumes:
      - ./gorm.db:/app/data/gorm.db
    ports:
      - "8081:8080"
    depends_on:
      - redis

  app2:
    build: .
    container_name: app2
    volumes:
      - ./gorm.db:/app/data/gorm.db
    ports:
      - "8082:8080"
    depends_on:
      - redis


  app3:
    build: .
    container_name: app3
    volumes:
      - ./gorm.db:/app/data/gorm.db
    ports:
      - "8083:8080"
    depends_on:
      - redis

  app4:
    build: .
    container_name: app4
    volumes:
      - ./gorm.db:/app/data/gorm.db
    ports:
      - "8084:8080"
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
